### ISSUE TITLE
ERC20 swaps give wrong error when ETH funds lack

### ISSUE THREAD

**Issue by jorian** [particle4dev/hyperdex#17]
<img width="389" alt="image" src="https://user-images.githubusercontent.com/10341677/68935656-33e11080-0799-11ea-8557-6fd735f7c1f1.png">

while stdout gives: 

```
mm › 15 10:12:56, rpc:312] RPC error response: rpc:281] eth:1788] Base coin balance 0 is too low to cover gas fee, required 0.0002
```

This simply means that in order to swap ERC20 coins, the user needs to have ETH balance. Maybe a simple check can be built for this? 

if coin === erc20 then if eth balance < 0.001 then throw error?

**Comment by particle4dev** [comment]
@jorian I think we should enable ETH by default first
