### ISSUE TITLE
order not cancellable, not in mm2.0 response but still visible

### ISSUE THREAD

**Issue by jorian** [particle4dev/hyperdex#19]
The GUI leaves an order open, while the order does not exist in the response from mm2.0 anymore:

![image](https://user-images.githubusercontent.com/10341677/69052595-ba028e80-0a07-11ea-9600-246eb228ae37.png)

&

![image](https://user-images.githubusercontent.com/10341677/69052699-f7ffb280-0a07-11ea-84ee-61b2879940bf.png)

while a recent `my_orders` call to mm2.0 yields this response:

![image](https://user-images.githubusercontent.com/10341677/69052631-cdadf500-0a07-11ea-814b-0a18a7cfb80c.png)

![image](https://user-images.githubusercontent.com/10341677/69052647-d4d50300-0a07-11ea-8f51-1b3e90a71d4b.png)

The GUI probably has an await still open, because the Buy button is now disabled. 

![image](https://user-images.githubusercontent.com/10341677/69053540-ed461d00-0a09-11ea-97dd-8b098789796b.png)

Somewhere the GUI thinks there is still an order active, while there actually aren't any orders active anymore. This order probably got added to a local DB, but didn't get properly removed together with mm2.0 removing the order. 

I would say there can't be 2 truths, maybe refactor the `Open Order` part to always mirror the response from mm2.0? (maybe this should be its own issue then...)

**Comment by particle4dev** [comment]
hi @jorian
could you share how your order looks like in local DB?
(you can get it by running this command in your console)
```
_swapDB.getOrders().then(e => console.log(e))
```
Does this error only occur with ERC20 token?
I will take a look at this tomorrow

**Comment by jorian** [comment]
It might be an edge case, because other swaps I did today, finished just fine. It seems this order got in a limbo state. 

However, other DAI/KMD trades are now not possible; the buy button stays greyed out and the stdout tells me that it can't find the order that is still open in the GUI.

This is the response for the swapDB.getorders()

![image](https://user-images.githubusercontent.com/10341677/69083203-f18e2c80-0a41-11ea-960b-bed718ac64ce.png)

**Comment by particle4dev** [comment]
hi @jorian,
I just pushed some code to fix this
please test and see if this issue persists
thanks

**Comment by jorian** [comment]
The order that was stuck for a couple of days is now gone. I will test the set-order functionality some more in the coming days.

**Comment by particle4dev** [comment]
cool, I will close this issue for now
please reopen if it persists
