### ISSUE TITLE
clicking Price in orderbook section populates a too high buy Price

### ISSUE THREAD

**Issue by jorian** [particle4dev/hyperdex#22]
![image](https://user-images.githubusercontent.com/10341677/69067146-e5df3d80-0a22-11ea-839f-00c43b55b62d.png)

Clicking the `Price KMD` in the orderbook table, populates the `Price KMD` in the buy section. However, the price that is populated is too high. It should be the exact same amount; the same functionality as already exists when users click on the `target` symbol button:

![image](https://user-images.githubusercontent.com/10341677/69067282-18893600-0a23-11ea-83fb-f1201402a7f9.png)

resulting in

![image](https://user-images.githubusercontent.com/10341677/69067309-22ab3480-0a23-11ea-97cf-66bc2977a5fe.png)

**Comment by particle4dev** [comment]
@jorian currently, hyperdex team set the price 5% more expensive to increase match rate.
Do you want me to set it lower?
Link to the code: https://github.com/particle4dev/hyperdex/blob/master/app/renderer/views/Exchange/Order.js#L68

**Comment by particle4dev** [comment]
@jorian I just changed the price down to 0.1% more expensive
please do a test and let me know what you think
close issue for now

**Comment by jorian** [comment]
0.1% is fine.
