### ISSUE TITLE
withdraw confirmation screen shows wrong information

### ISSUE THREAD

**Issue by jorian** [particle4dev/hyperdex#27]
The initial window is like this:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/10341677/69374815-3535a000-0ca7-11ea-8c9b-e341603431c1.png">

Enter an address and an amount:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/10341677/69374860-4da5ba80-0ca7-11ea-8298-7ee2395576c2.png">

Still fine by now. Now the user needs to click on the Withdraw button:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/10341677/69374885-61512100-0ca7-11ea-97f2-c039bd3103d1.png">

A confirmation screen appears, where `Remaining balance` now shows a wrong amount. It should be 2050.xxx, but it shows 2041.xxx. It's as if instead of 1, it subtracts 10.

**Comment by particle4dev** [comment]
hi @jorian 
I can't reproduce this issue.
It shows "Nan" instead on my app
I noticed that fee is a string instead of a number in withdraw response
Just fixed it
Please test and reopen this if the issue still persists on your app
